name: titanic-capstone-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - django
  - whitenoise

  # Core data science
  - numpy
  - pandas
  - scikit-learn

  # Visualization
  - matplotlib
  - seaborn

  # Jupyter
  - notebook
  - ipykernel

  # Utilities
  - pip

  # Pip packages (if needed)
  - pip:
      - joblib
      - python-dotenv
