name: Deploy Titanic Django to Azure 
on:
  push:
    branches:
      - development
      - feature/ci-azure
    paths:
      - 'web/**'  # Only trigger if files in web/ change

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version : '3.12'

      - name: Install dependencies    
        run: |
            python -m pip install --upgrade pip
            pip install -r web/requirements.txt
          
      - name: Check Python and Django
        run: |
          python --version
          python -m pip show django
      
      - name: Copy ML model
        run: |
          mkdir -p web/predictor/ml_models
          cp models/titanic_model_LR.pkl web/predictor/ml_models/

      - name: Collect Django static files
        run: |
          cd web
          python manage.py collectstatic --noinput
          python manage.py migrate          

      # Deploy to Azure (only for dev)
      - name: Deploy to Azure Web App
        if: github.ref_name == 'development'
        uses: azure/webapps-deploy@v2
        with:
          app-name: titanic-ml-app
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: web
